name: Coverity Scan
on:
  push:
    branches: [ "main" ]
jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    
      - name: Dependencies
        run: >
            sudo apt-get install build-essential git make
            pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev
            libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev
            libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev
            libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev
            libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev
    
      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: >
            cmake -B ${{ steps.strings.outputs.build-output-dir }}
            -DCMAKE_CXX_COMPILER=g++
            -DCMAKE_C_COMPILER=gcc
            -DCMAKE_BUILD_TYPE=Release
            -S ${{ github.workspace }}
      - uses: vapier/coverity-scan-action@v1
        with:
          email: ${{ secrets.COVERITY_SCAN_EMAIL }}
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          command: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release