name: Tests
on: [push, pull_request]
jobs:
  msvc:
    strategy:
      matrix:
        version: [14.29, ""]
      fail-fast: false
    name: "MSVC ${{ matrix.version }} (C++20)"
    runs-on: windows-2022
    steps:
      - name: Add MSVC ${{ matrix.version }} to PATH
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: ${{ matrix.version }}
      - name: "Install CMake"
        run: choco install cmake
      - uses: actions/checkout@v2
      - name: "Configure"
        working-directory: tests
        run: cmake -S . -B build
      - name: "Build"
        working-directory: tests
        run: cmake --build build --verbose
      - name: "Run tests"
        working-directory: tests
        run: build/Debug/tests.exe
